spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fitness-oauth2-auth
          jwk-set-uri: http://localhost:8080/realms/fitness-oauth2-auth/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita descoberta automática de serviços
      routes:
        - id: userserver
          uri: lb://USERSERVER
          predicates:
            - Path=/api/users/**
        - id: activityservice
          uri: lb://ACTIVITYSERVICE
          predicates:
            - Path=/api/activities/**
        - id: aiservice
          uri: lb://AISERVICE
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true