spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/activities
      database: activities
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
