spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/activity
      database: activities

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/